name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  test:
    uses: ./.github/workflows/test.yaml
    needs: [build]

  lint:
    uses: ./.github/workflows/lint.yaml
    needs: [build]
    secrets: inherit
