name: Lint
on:
    workflow_dispatch:
    workflow_call:

permissions:
    contents: read

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version: "1.24"

            - name: golangci-lint
              uses: golangci/golangci-lint-action@v6

    sonarqube:
        name: SonarQube
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-go@v5
              with:
                  go-version: "1.24"
            - name: Detect Code Coverage
              run: mkdir -p bin && go test -coverprofile bin/cov.out ./...
            - name: SonarQube Scan
              uses: SonarSource/sonarqube-scan-action@v5.3.1
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
