name: Test
on:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    name: Test (Unit)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Test
        run: go test -v ./...
